# Generated by Django 2.1 on 2021-10-25 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20191128_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='init_balance',
            field=models.FloatField(default=0.0, verbose_name='Initial Balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='acct_balance',
            field=models.FloatField(default=0.0, verbose_name='Current Balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='acct_source',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Source/Institution'),
        ),
        migrations.AlterField(
            model_name='account',
            name='acct_type',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_date',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='transaction date'),
        ),
    ]
